/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package primzahl;

/**
 *
 * @author m.mez
 */
public class wetterstation extends javax.swing.JFrame {

    /** Creates new form wetterstation */
    public wetterstation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wetterstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wetterstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wetterstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wetterstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wetterstation().setVisible(true);

                int[] Tag = {1,2,3,4,5,6,7,8,9,10,11,12,13,14};
                int[] Temperatur = {12, 14, 9, 12, 15, 16, 15, 15, 11, 8, 13, 13, 15, 12};

                //Durchschnittstemperatur bestimmen
                int Durchschnitt = 0;
                int Summe = 0;
                for(int i=0; i<Temperatur.length; i++){
                    Summe += Temperatur[i];
                }
                Durchschnitt = Summe / Temperatur.length;
                System.out.println("Die Durchschnittstemperatur beträgt: " + Durchschnitt + " °" );
                
                // Max Temperatur und Min Temperatur
                int Min = 20;
                int Max = 0;
                for(int i=0; i<Temperatur.length; i++){
                    if(Temperatur[i] > Max){
                        Max = Temperatur[i];
                    }
                    else{
                        Max = Max;
                    }
                
                }
                System.out.println("Die Höchsttemperatur Beträgt: "+ Max +" °");
                for(int i=0; i<Temperatur.length; i++){
                    if(Temperatur[i] < Min){
                        Min = Temperatur[i];
                    }
                    else{
                        Min = Min;
                    }
                
                }
                System.out.println("Die kälteste Temperatur ist: "+ Min +" °");
                
                // Größte Schwankung
                int maxSchwankung = 0;
                for(int i=0; i<Temperatur.length - 1; i++){
                    int derzeitige_Schwankung = Temperatur[i] - Temperatur[i + 1];
                    if(derzeitige_Schwankung < 0){
                        derzeitige_Schwankung = derzeitige_Schwankung * -1;
                    }
                    else{
                        if(derzeitige_Schwankung > maxSchwankung){
                            maxSchwankung = derzeitige_Schwankung;
                                 
                        }else{
                            maxSchwankung = maxSchwankung;
                        }
                    }
                    
                }
                System.out.println("Die Größte Sschwankung beträgt: " + maxSchwankung + " °");
                System.out.println("Tag   Temp");
                for(int i=0; i<Temperatur.length; i++){
                    if(i <= 8){
                       System.out.println(Tag[i] + "      " + Temperatur[i]); 
                    }
                    else{
                      System.out.println(Tag[i] + "     " + Temperatur[i]);   
                    }
                    
                    
                }    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
